import { getLocationOrigin } from 'next/dist/shared/lib/utils'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from './login-panel'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">News</a>!
        </h1>

        <p className={styles.description}>
          News for You!
        </p>
        
        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Title &rarr;</h2>
          </a>

          <a  className={styles.card}>
            <h2>Title &rarr;</h2>
          </a>

          <a className={styles.card}>
            <h2>Title &rarr;</h2>

          </a>

          <a className={styles.card}>
            <h2>Title &rarr;</h2>
          </a>
        </div>

        <div>
          <button onClick={()=>{window.location.href="/login-panel"}}>Log In</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    
  )
  
}
